project_id = "supabase_id"

[functions.check-api-username]
verify_jwt = false

[functions.test-api]
verify_jwt = false

[functions.user]
verify_jwt = false

[functions.saved]
verify_jwt = false

[functions.stats]
verify_jwt = false
